spring:
  datasource:
    url: jdbc:mysql://192.168.1.7:3306/regulus
    username: regulus  # 数据库用户名
    driver-class-name: com.mysql.cj.jdbc.Driver  #
    password: regnalswn
  flyway:
    user: regulus
    password: regnalswn


bot:
  appId: 102605333
  secret: 6iKwYAmO0dGtW9mP3hLzdHvZEtYDsXCs